import marimo

__generated_with = "0.23.6"
app = marimo.App(width="medium")


@app.cell
def _():
    import dlt
    import marimo as mo
    from dlt.sources.helpers import requests
    from dlt.sources.helpers.rest_client import RESTClient
    from dlt.sources.helpers.rest_client.paginators import JSONLinkPaginator
    from pydantic import AnyHttpUrl, BaseModel, ConfigDict

    return dlt, mo, requests


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    # Section 03: DLT basics

    In the previous sections, we collected Pokemon data manually with `requests` and used Pydantic to validate the API responses.

    The manual collector used two different API endpoints.

    - Fetch the paginated Pokemon list.
    - Fetch each Pokemon detail resource from the `url` field.

    In this section, we will replace the manual collection code with DLT. But first...

    ## What Is DLT?
    [dlt](https://github.com/dlt-hub/dlt) is an open-source Python library that loads data from various, often messy data sources into well-structured datasets. It provides lightweight Python interfaces to extract, load, inspect, and transform data. The dlt documentation and tooling are designed to work well with LLM-assisted workflows, helping you move from pipeline code to usable data in a notebook.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ## Learning goals

    By the end of this section, you should be able to:

    - Define a custom DLT source
    - Add a DLT resource
    - Add a DLT transformer
    - Use DLT's REST client pagination
    - Run a small DLT pipeline locally
    - Inspect the collected Pokemon detail records
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## DLT pipeline

    Let's start by defining a DLT pipeline. A pipeline is configured by setting a pipeline name, destination, and dataset name. In the following example, we'll configure a pipeline to store our collected resources in [DuckDB](https://duckdb.org/), an embedded analytical database.

    *Note*: OpenHound configures the pipeline automatically using the filesystem destination.
    """)
    return


@app.cell
def _(dlt):
    pipeline = dlt.pipeline(
        pipeline_name="workshop",
        destination="duckdb",
        dataset_name="pokemon",
    )
    return (pipeline,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## DLT resources
    Next we'll write the collection logic using DLT resources and transformers. A DLT resource is a Python function wrapped with the `@dlt.resource` decorator containing the necessary logic to collect data from, in this case, an API endpoint. Each resource typically returns one specific data type. In the case of the Pokemon dataset, a Pokemon, a town, and a berry would be defined as three individual resources. Let's re-implement our basic Pokemon collector from the first section of the workshop.
    """)
    return


@app.cell
def _(dlt, pipeline, requests):
    POKEMON_PAGE_URL = "https://pokeapi.co/api/v2/pokemon"

    @dlt.resource(table_name="pokemon")
    def pokemon():
        response = requests.get(POKEMON_PAGE_URL).json()
        yield response["results"]

    pipeline.run(pokemon)
    return (pokemon,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Now let's inspect the collected data. You can directly load the collected data as a dataframe using DLT's built-in methods. The output should look familiar, with two additional columns generated by DLT. There should only be 180 Pokemon in the list because we haven't added pagination yet. This will be done later.
    """)
    return


@app.cell
def _(pipeline):
    pipeline.dataset().pokemon.df()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## DLT transformers

    You probably remember from the previous section that we still need to collect the Pokemon details. Using DLT, we can define a `@dlt.transformer` function. A transformer takes data from an upstream resource for additional processing. Take a look at the example below, where we define a new transformer that uses the output from the previous `pokemon` resource.
    """)
    return


@app.cell
def _(dlt, pipeline, pokemon, requests):
    @dlt.transformer(
        table_name="pokemon_details",
        parallelized=True,
        max_table_nesting=0,
        write_disposition="replace",
    )
    def pokemon_details(pokemons: list):
        @dlt.defer
        def _get_pokemon_details(_pokemon):
            return requests.get(_pokemon["url"]).json()

        # For every Pokemon in our list, run _get_pokemon_details asynchronously
        for _pokemon in pokemons:
            yield _get_pokemon_details(_pokemon)

    pokemon_with_details = pokemon | pokemon_details
    pipeline.run(pokemon_with_details)
    return (pokemon_details,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    The `pokemon_with_details` variable defines a direct relationship between `pokemon` and `pokemon_details`. This means that for every result yielded by the `pokemon` resource, the data is passed to the `pokemon_details` transformer for further processing. No need to think about parallelization yourself.

    Some additional context:
    - By passing the `parallelized=True` argument, we configure the transformer to run in a separate thread;
    - By configuring `max_table_nesting=0`, we enforce that nested data remains nested at the destination. The default behavior of DLT is to create multiple tables for nested data.
    - The `@dlt.defer` decorator allows us to run a function asynchronously inside our transformer. This means we won't have to wait for API requests to finish before collecting details for the next Pokemon.
    - The `write_disposition="replace"` setting ensures we overwrite data in our DuckDB database instead of appending new records.
    """)
    return


@app.cell
def _(pipeline):
    pipeline.dataset().pokemon_details.df()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Exercise 1: Remember those Pydantic models?
    During the previous workshop section, we defined multiple Pydantic models for the Pokemon dataset. Define those models again and modify the existing `pokemon` resource and `pokemon_details` transformer to use the Pydantic model for validation. Here is an example to get you started:

    ```py
    class Pokemon(BaseModel):
        name: str
        url: AnyHttpUrl

    @dlt.resource(table_name="pokemon", columns=Pokemon)
    def pokemon():
        response = requests.get(POKEMON_PAGE_URL).json()
        yield response["results"]
    ```

    DLT supports using Pydantic models natively via the `columns=` parameter on resources and transformers. These models will validate all records yielded by DLT before they are written to the destination.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Combining erything With DLT sources
    A DLT source defines your custom collector, its required settings, and which resources to collect. By implementing a DLT source, we can collect all resources defined by the Pokemon source via a single entry point.

    This also allows us to create a shared client that can be reused across all resources and transformers based on the provided configuration parameters.
    """)
    return


@app.cell
def _(dlt, pipeline, pokemon, pokemon_details):
    @dlt.source(name="poke_api")
    def poke_api():
        return pokemon | pokemon_details

    pipeline.run(poke_api)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    The output should match our previous per-resource collection attempts, but now managed via a single DLT source entry point.
    """)
    return


@app.cell
def _(pipeline):
    pipeline.dataset().pokemon_details.df()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Exercise 2: DLT config / resource parameters
    The current `poke_api` source definition is relatively straightforward: it only defines a name and a set of resources. Add a DLT configuration parameter named `limit` to the `poke_api` source and ensure that only the specified number of Pokemon are collected.

    Use the following pages to get started:
    - Adding limits to resources: https://dlthub.com/docs/general-usage/resource
    - Adding config/secrets to a source: https://dlthub.com/docs/general-usage/credentials/setup#configure-both-config-and-secrets
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ## DLT RESTClient


    We're almost there, we still need to implement pagination. In case you forgot, the API returns the following pagination metadata:

    ```json
    {
      "count": 1350,
      "next": "https://pokeapi.co/api/v2/pokemon?offset=100&limit=100",
      "previous": null,
      "results": []
    }
    ```

    In the first section of the workshop, we implemented a method to collect the Pokemon pages until the `next` field was empty. Now let's take a look at DLT's RESTClient to make this process easier.

    The [RESTClient](https://dlthub.com/docs/general-usage/http/rest-client) class offers an interface for interacting with RESTful APIs, including features like:
    - Automatic pagination
    - Various authentication mechanisms
    - Customizable request/response handling

    Now let's take a look at the following RESTClient example, with built-in pagination support and the `BASE_URI` of the PokeAPI.

    ```python
    POKEMON_API_BASE_URL = "https://pokeapi.co/api/v2/"

    pokemon_client = RESTClient(
        base_url=POKEMON_API_BASE_URL,
        paginator=JSONLinkPaginator(next_url_path="next"),
    )
    ```
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    The `JSONLinkPaginator` paginator expects the link to the next page to be included in the JSON response. By specifying `next_url_path="next"`, we specify that the URL to the next page can be found in the API response's `next` field.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Exercise 3: Adding pagination support
    Use the example RESTClient shown in the cell above. See if you can modify the existing `pokemon` resource and the `pokemon_details` transformer to make use of a shared client instead of `requests`. Use the following reference for details on how pagination works: https://dlthub.com/docs/general-usage/http/rest-client
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ## Inspecting the final results

    At the end of this section, you should see all 1000+ Pokemon including their details. If the cell below shows only 20 rows, you're still missing 980+ Pokemon!
    """)
    return


@app.cell
def _(pipeline):
    pipeline.dataset().pokemon_details.df()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md("""
    ## Wrapping Up

    In this section, we replaced manual collection code with a minimal DLT pipeline. Next, we can use this same resource and transformer pattern as part of an OpenHound collector.
    """)
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
